-- 한 줄 주석
/* 
 * 범위주석
 * 
 */


ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
-- 선택한 SQL 수행 : 구문 커서 두시고 CTRL + ENTER

CREATE USER kh_jds IDENTIFIED BY kh1234;

GRANT RESOURCE, CONNECT TO kh_jds;

ALTER USER kh_jds DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;